import { formatDateOnly } from '../utils/date-format';

/**
 * Team-ready executive summary security report.
 * Shorter, business-focused version of the full report.
 */

export interface ExecutiveSummary {
  organization: string;
  reportDate: string;
  totalExtensions: number;
  totalRiskScore: number;
  averageRiskScore: number;
  riskBreakdown: {
    low: number;
    moderate: number;
    high: number;
    critical: number;
  };
  topFindings: string[];
  recommendations: string[];
  complianceStatus: 'pass' | 'warn' | 'fail';
  policyViolations: number;
}

export function generateExecutiveSummary(summary: {
  totalExtensions: number;
  lowRisk: number;
  moderateRisk: number;
  highRisk: number;
  criticalRisk: number;
  reports: Array<{
    name: string;
    publisher: string;
    version: string;
    riskScore: number;
    riskLevel: string;
    recommendation: string;
    riskFactors: Array<{ title: string; severity: string }>;
    detectedCapabilities: Record<string, boolean>;
  }>;
  scannedAt: string;
}): ExecutiveSummary {
  const totalScore = summary.reports.reduce((s, r) => s + r.riskScore, 0);
  const avgScore =
    summary.totalExtensions > 0
      ? Math.round(totalScore / summary.totalExtensions)
      : 0;

  const highRiskCount = summary.reports.filter(
    (r) => r.riskLevel === 'high' || r.riskLevel === 'critical',
  ).length;
  const findings: string[] = [];

  if (highRiskCount > 0) {
    findings.push(
      `${highRiskCount} extension(s) flagged as high/critical risk requiring immediate review`,
    );
  }

  const withShell = summary.reports.filter(
    (r) => r.detectedCapabilities?.usesChildProcess,
  ).length;
  if (withShell > 0)
    findings.push(`${withShell} extension(s) use shell execution capabilities`);

  const withNetwork = summary.reports.filter(
    (r) => r.detectedCapabilities?.usesNetworkRequests,
  ).length;
  if (withNetwork > 0)
    findings.push(`${withNetwork} extension(s) make network requests`);

  const withObfuscation = summary.reports.filter(
    (r) => r.detectedCapabilities?.hasObfuscatedCode,
  ).length;
  if (withObfuscation > 0)
    findings.push(`${withObfuscation} extension(s) contain obfuscated code`);

  const recs: string[] = [];
  if (highRiskCount > 0)
    recs.push(
      `Review and potentially disable ${highRiskCount} high-risk extension(s)`,
    );
  if (summary.moderateRisk > 3)
    recs.push(`Audit ${summary.moderateRisk} moderate-risk extensions`);

  const complianceStatus =
    summary.criticalRisk > 0 ? 'fail' : summary.highRisk > 0 ? 'warn' : 'pass';

  return {
    organization: 'VS Code Workspace',
    reportDate: new Date(summary.scannedAt).toISOString(),
    totalExtensions: summary.totalExtensions,
    totalRiskScore: totalScore,
    averageRiskScore: avgScore,
    riskBreakdown: {
      low: summary.lowRisk,
      moderate: summary.moderateRisk,
      high: summary.highRisk,
      critical: summary.criticalRisk,
    },
    topFindings: findings,
    recommendations: recs,
    complianceStatus,
    policyViolations: highRiskCount,
  };
}

export function generateExecutiveMarkdown(exec: ExecutiveSummary): string {
  let md = `# Shieldex Executive Security Summary\n\n`;
  md += `**Organization:** ${exec.organization}\n`;
  md += `**Date:** ${formatDateOnly(exec.reportDate)}\n`;
  md += `**Compliance Status:** ${exec.complianceStatus.toUpperCase()}\n\n`;
  md += `---\n\n`;
  md += `## Overview\n\n`;
  md += `- **Total Extensions:** ${exec.totalExtensions}\n`;
  md += `- **Average Risk Score:** ${exec.averageRiskScore}/100\n`;
  md += `- **Total Risk Score:** ${exec.totalRiskScore}\n\n`;

  md += `## Risk Breakdown\n\n`;
  md += `| Level | Count |\n`;
  md += `|-------|-------|\n`;
  md += `| Low | ${exec.riskBreakdown.low} |\n`;
  md += `| Moderate | ${exec.riskBreakdown.moderate} |\n`;
  md += `| High | ${exec.riskBreakdown.high} |\n`;
  md += `| Critical | ${exec.riskBreakdown.critical} |\n\n`;

  if (exec.topFindings.length > 0) {
    md += `## Top Findings\n\n`;
    for (const f of exec.topFindings) {
      md += `- ${f}\n`;
    }
    md += '\n';
  }

  if (exec.recommendations.length > 0) {
    md += `## Recommendations\n\n`;
    for (const r of exec.recommendations) {
      md += `- ${r}\n`;
    }
    md += '\n';
  }

  if (exec.policyViolations > 0) {
    md += `## ⚠ Policy Violations\n\n`;
    md += `${exec.policyViolations} extensions violate security policy.\n\n`;
  }

  md += `---\n\n`;
  md += `*Executive report generated by Shieldex*\n`;
  return md;
}
