import { formatDateTime } from '../utils/date-format';
import { EXT_CONFIG } from '../config';

export function generateMarkdownReport(summary: {
  totalExtensions: number;
  lowRisk: number;
  moderateRisk: number;
  highRisk: number;
  criticalRisk: number;
  reports: Array<{
    name: string;
    publisher: string;
    version: string;
    marketplaceId?: string;
    category?: string;
    iconDataUrl?: string;
    riskScore: number;
    riskLevel: string;
    riskFactors: Array<{ title: string; description: string }>;
    trustSignals: Array<{ title: string; description: string }>;
    extensionDependencies?: Array<{ name: string; version: string }>;
    recommendation: string;
  }>;
  scannedAt: string;
  vscodeVersion?: string;
}): string {
  const date = formatDateTime(summary.scannedAt);
  let md = `# ${EXT_CONFIG.name} Security Report\n\n`;
  md += `**Generated:** ${date}\n`;
  if (summary.vscodeVersion)
    md += `**VS Code Version:** ${summary.vscodeVersion}\n`;
  md += `\n---\n\n`;
  md += `## Summary\n\n`;
  md += `| Metric | Count |\n`;
  md += `|--------|-------|\n`;
  md += `| Total Extensions Scanned | ${summary.totalExtensions} |\n`;
  md += `| Low Risk | ${summary.lowRisk} |\n`;
  md += `| Moderate Risk | ${summary.moderateRisk} |\n`;
  md += `| High Risk | ${summary.highRisk} |\n`;
  md += `| Critical Risk | ${summary.criticalRisk} |\n\n`;
  md += `---\n\n`;

  if (summary.highRisk + summary.criticalRisk > 0) {
    md += `## High & Critical Risk Extensions\n\n`;
    const risky = summary.reports.filter(
      (r) => r.riskLevel === 'high' || r.riskLevel === 'critical',
    );
    for (const ext of risky) {
      md += `### ${formatMarkdownExtensionLink(ext.name, ext.marketplaceId, ext.publisher)}\n\n`;
      md += `- **Publisher:** ${ext.publisher}\n`;
      md += `- **Version:** ${ext.version}\n`;
      if (ext.marketplaceId)
        md += `- **Marketplace ID:** ${ext.marketplaceId}\n`;
      if (ext.category) md += `- **Category:** ${ext.category}\n`;
      md += `- **Risk Score:** ${ext.riskScore}/100\n`;
      md += `- **Risk Level:** ${ext.riskLevel.toUpperCase()}\n\n`;
      md += `**Risk Factors:**\n`;
      for (const f of ext.riskFactors) {
        md += `- ${f.title}: ${f.description}\n`;
      }
      md += `\n**Recommendation:** ${ext.recommendation}\n\n`;
    }
  }

  md += `---\n\n`;
  md += `## All Extensions\n\n`;
  md += `| Extension | Publisher | Version | Risk Score | Risk Level |\n`;
  md += `|-----------|-----------|---------|------------|------------|\n`;
  for (const ext of summary.reports) {
    md += `| ${formatMarkdownExtensionLink(ext.name, ext.marketplaceId, ext.publisher)} | ${ext.publisher} | ${ext.version} | ${ext.riskScore} | ${ext.riskLevel} |\n`;
  }

  md += `\n---\n\n`;
  md += `*Report generated by ${EXT_CONFIG.name}*\n`;
  return md;
}

export function generateJsonReport(summary: {
  totalExtensions?: number;
  lowRisk?: number;
  moderateRisk?: number;
  highRisk?: number;
  criticalRisk?: number;
  scannedAt?: string;
  vscodeVersion?: string;
  reports?: Array<Record<string, unknown>>;
}): string {
  return JSON.stringify(normalizeExportSummary(summary), null, 2);
}

export function generateHtmlReport(summary: {
  totalExtensions: number;
  lowRisk: number;
  moderateRisk: number;
  highRisk: number;
  criticalRisk: number;
  reports: Array<{
    name: string;
    publisher: string;
    version: string;
    marketplaceId?: string;
    category?: string;
    iconDataUrl?: string;
    riskScore: number;
    riskLevel: string;
    riskFactors: Array<{ title: string; description: string }>;
    trustSignals: Array<{ title: string; description: string }>;
    extensionDependencies?: Array<{ name: string; version: string }>;
    recommendation: string;
  }>;
  scannedAt: string;
  vscodeVersion?: string;
}): string {
  const date = formatDateTime(summary.scannedAt);
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${EXT_CONFIG.name} Security Report</title>
  <style>
    body { font-family: -apple-system, system-ui, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #333; }
    h1 { border-bottom: 2px solid #007acc; padding-bottom: 10px; }
    .meta { color: #666; margin-bottom: 24px; }
    .summary { display: flex; gap: 16px; margin: 20px 0; flex-wrap: wrap; }
    .card { padding: 16px 24px; border-radius: 8px; text-align: center; min-width: 100px; }
    .card .count { font-size: 2em; font-weight: bold; }
    .card .label { font-size: 0.85em; opacity: 0.8; }
    .card.low { background: #e8f5e9; color: #2e7d32; }
    .card.moderate { background: #fff3e0; color: #e65100; }
    .card.high { background: #ffebee; color: #c62828; }
    .card.critical { background: #f3e5f5; color: #6a1b9a; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { text-align: left; padding: 10px 12px; border-bottom: 1px solid #ddd; }
    th { background: #f5f5f5; font-weight: 600; }
    .ext-link { display: inline-flex; align-items: center; gap: 10px; color: inherit; text-decoration: none; }
    .ext-link:hover { text-decoration: underline; }
    .ext-icon-wrap { width: 24px; height: 24px; flex: 0 0 24px; border-radius: 6px; overflow: hidden; background: rgba(0,0,0,0.06); display: inline-flex; align-items: center; justify-content: center; }
    .ext-icon { width: 100%; height: 100%; object-fit: cover; display: block; }
    .ext-icon-fallback { font-size: 10px; font-weight: 700; color: #555; text-transform: uppercase; }
    .badge { display: inline-block; padding: 3px 10px; border-radius: 4px; font-size: 0.8em; font-weight: 600; color: #fff; }
    .badge.low { background: #4caf50; }
    .badge.moderate { background: #ff9800; }
    .badge.high { background: #f44336; }
    .badge.critical { background: #9c27b0; }
    .ext-section { margin: 24px 0; padding: 16px; border-left: 4px solid #ddd; background: #fafafa; }
    .ext-section.risky { border-left-color: #f44336; background: #fff5f5; }
    footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #ddd; color: #888; font-size: 0.85em; }
  </style>
</head>
<body>
  <h1>${EXT_CONFIG.name} Security Report</h1>
  <div class="meta">
    <p><strong>Generated:</strong> ${date}</p>
    ${summary.vscodeVersion ? `<p><strong>VS Code:</strong> ${summary.vscodeVersion}</p>` : ''}
  </div>

  <div class="summary">
    <div class="card"><div class="count">${summary.totalExtensions}</div><div class="label">Total</div></div>
    <div class="card low"><div class="count">${summary.lowRisk}</div><div class="label">Low</div></div>
    <div class="card moderate"><div class="count">${summary.moderateRisk}</div><div class="label">Moderate</div></div>
    <div class="card high"><div class="count">${summary.highRisk}</div><div class="label">High</div></div>
    <div class="card critical"><div class="count">${summary.criticalRisk}</div><div class="label">Critical</div></div>
  </div>

  <h2>All Extensions</h2>
  <table>
    <thead><tr><th>Extension</th><th>Publisher</th><th>Version</th><th>Risk Score</th><th>Risk Level</th></tr></thead>
    <tbody>
      ${summary.reports
        .map(
          (r) => `<tr>
        <td><a class="ext-link" href="${getMarketplaceUrl(r.marketplaceId, r.publisher, r.name)}" target="_blank" rel="noopener noreferrer">${renderHtmlReportIcon(r.name, r.iconDataUrl)}<span>${escapeHtml(r.name)}</span></a></td><td>${escapeHtml(r.publisher)}</td><td>${escapeHtml(r.version)}</td>
        <td>${r.riskScore}</td>
        <td><span class="badge ${r.riskLevel}">${r.riskLevel.toUpperCase()}</span></td>
      </tr>`,
        )
        .join('')}
    </tbody>
  </table>

  ${summary.reports
    .filter((r) => r.riskLevel === 'high' || r.riskLevel === 'critical')
    .map(
      (r) => `
    <div class="ext-section risky">
      <h3><a class="ext-link" href="${getMarketplaceUrl(r.marketplaceId, r.publisher, r.name)}" target="_blank" rel="noopener noreferrer">${renderHtmlReportIcon(r.name, r.iconDataUrl)}<span>${escapeHtml(r.name)}</span></a> <span class="badge ${r.riskLevel}">${r.riskLevel.toUpperCase()}</span></h3>
      <p><strong>Publisher:</strong> ${escapeHtml(r.publisher)} | <strong>Version:</strong> ${escapeHtml(r.version)} | <strong>Score:</strong> ${r.riskScore}/100</p>
      ${r.riskFactors.length > 0 ? `<p><strong>Risk Factors:</strong> ${r.riskFactors.map((f) => escapeHtml(f.title)).join(', ')}</p>` : ''}
      <p><strong>Recommendation:</strong> ${escapeHtml(r.recommendation)}</p>
    </div>
  `,
    )
    .join('')}

  <footer>Report generated by ${EXT_CONFIG.name}</footer>
</body>
</html>`;
}

export function generateCsvReport(summary: {
  reports: Array<{
    name: string;
    publisher: string;
    version: string;
    marketplaceId?: string;
    category?: string;
    riskScore: number;
    riskLevel: string;
    riskFactors: Array<{ title: string }>;
    recommendation: string;
  }>;
}): string {
  const headers = [
    'Extension',
    'Publisher',
    'Version',
    'MarketplaceID',
    'MarketplaceUrl',
    'Category',
    'RiskScore',
    'RiskLevel',
    'RiskFactors',
    'Recommendation',
  ];
  let csv = headers.join(',') + '\n';

  for (const r of summary.reports) {
    const row = [
      escapeCsv(r.name),
      escapeCsv(r.publisher),
      escapeCsv(r.version),
      escapeCsv(r.marketplaceId || ''),
      escapeCsv(getMarketplaceUrl(r.marketplaceId, r.publisher, r.name)),
      escapeCsv(r.category || ''),
      r.riskScore.toString(),
      r.riskLevel,
      escapeCsv(r.riskFactors.map((f) => f.title).join('; ')),
      escapeCsv(r.recommendation),
    ];
    csv += row.join(',') + '\n';
  }

  return csv;
}

function escapeCsv(val: string): string {
  if (val.includes(',') || val.includes('"') || val.includes('\n')) {
    return `"${val.replace(/"/g, '""')}"`;
  }
  return val;
}

function getMarketplaceUrl(
  marketplaceId: string | undefined,
  publisher: string,
  name: string,
): string {
  const itemName = marketplaceId || `${publisher}.${name}`;
  return `https://marketplace.visualstudio.com/items?itemName=${encodeURIComponent(itemName)}`;
}

function formatMarkdownExtensionLink(
  name: string,
  marketplaceId: string | undefined,
  publisher: string,
): string {
  return `[${name}](${getMarketplaceUrl(marketplaceId, publisher, name)})`;
}

function renderHtmlReportIcon(name: string, iconDataUrl?: string): string {
  if (iconDataUrl) {
    return `<span class="ext-icon-wrap"><img class="ext-icon" src="${escapeHtmlAttribute(iconDataUrl)}" alt="" /></span>`;
  }

  const fallback = escapeHtml(name.slice(0, 2).toUpperCase() || '?');
  return `<span class="ext-icon-wrap"><span class="ext-icon-fallback">${fallback}</span></span>`;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function escapeHtmlAttribute(value: string): string {
  return escapeHtml(value).replace(/'/g, '&#39;');
}

function normalizeExportSummary(summary: {
  totalExtensions?: number;
  lowRisk?: number;
  moderateRisk?: number;
  highRisk?: number;
  criticalRisk?: number;
  scannedAt?: string;
  vscodeVersion?: string;
  reports?: Array<Record<string, unknown>>;
}): Record<string, unknown> {
  const reports = Array.isArray(summary.reports) ? summary.reports : [];
  return {
    totalExtensions: summary.totalExtensions ?? 0,
    lowRisk: summary.lowRisk ?? 0,
    moderateRisk: summary.moderateRisk ?? 0,
    highRisk: summary.highRisk ?? 0,
    criticalRisk: summary.criticalRisk ?? 0,
    scannedAt: summary.scannedAt ?? '',
    vscodeVersion: summary.vscodeVersion ?? '',
    reports: reports.map((report) => ({
      ...report,
      marketplaceUrl: getMarketplaceUrl(
        report.marketplaceId as string | undefined,
        String(report.publisher || ''),
        String(report.name || ''),
      ),
    })),
  };
}

export interface SarifReport {
  $schema: string;
  version: string;
  runs: Array<{
    tool: {
      driver: {
        name: string;
        version: string;
        informationUri: string;
        rules: any[];
      };
    };
    results: any[];
    invocations: Array<{
      executionSuccessful: boolean;
      toolExecutionNotifications: any[];
    }>;
  }>;
}

export function generateSarifReport(summary: {
  reports: Array<{
    name: string;
    publisher: string;
    version: string;
    marketplaceId?: string;
    riskScore: number;
    riskLevel: string;
    riskFactors: Array<{
      id: string;
      title: string;
      description: string;
      severity: string;
      evidence?: string[];
    }>;
    detectedCapabilities: Record<string, boolean>;
    installPath: string;
    recommendation: string;
  }>;
  scannedAt: string;
}): SarifReport {
  const sarifSeverityToLevel: Record<string, string> = {
    low: 'note',
    medium: 'warning',
    high: 'error',
    critical: 'error',
  };

  const rules: any[] = [];
  const results: any[] = [];

  for (const ext of summary.reports) {
    for (const factor of ext.riskFactors) {
      const ruleId = factor.id;

      if (!rules.find((r) => r.id === ruleId)) {
        rules.push({
          id: ruleId,
          name: factor.title,
          shortDescription: { text: factor.description },
          defaultConfiguration: {
            level: sarifSeverityToLevel[factor.severity] || 'warning',
          },
        });
      }

      results.push({
        ruleId,
        level: sarifSeverityToLevel[factor.severity] || 'warning',
        message: {
          text: `[${ext.publisher}.${ext.name}@${ext.version}] ${factor.title}: ${factor.description}`,
        },
        locations: [
          {
            physicalLocation: {
              artifactLocation: { uri: ext.installPath },
              region: { startLine: 1 },
            },
          },
        ],
        properties: {
          extensionId: ext.marketplaceId || `${ext.publisher}.${ext.name}`,
          marketplaceUrl: getMarketplaceUrl(
            ext.marketplaceId,
            ext.publisher,
            ext.name,
          ),
          riskScore: ext.riskScore,
          riskLevel: ext.riskLevel,
          evidence: factor.evidence || [],
        },
      });
    }
  }

  return {
    $schema:
      'https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json',
    version: '2.1.0',
    runs: [
      {
        tool: {
          driver: {
            name: EXT_CONFIG.name,
            version: '0.1.0',
            informationUri: `https://github.com/kiron0/${EXT_CONFIG.name.toLowerCase()}`,
            rules,
          },
        },
        results,
        invocations: [
          {
            executionSuccessful: true,
            toolExecutionNotifications: [],
          },
        ],
      },
    ],
  };
}
